export const RTC_OFFER_OPTION = {}
export const enum EventsEnum {
  SET_OFFER_DESCRIPTION = 'SET_OFFER_DESCRIPTION',
  SET_ANSWER_DESCRIPTION = 'SET_ANSWER_DESCRIPTION',
  SET_REMOTE_ICE_CANDIDATE = 'SET_REMOTE_ICE_CANDIDATE',
  SET_LOCAL_ICE_CANDIDATE = 'SET_LOCAL_ICE_CANDIDATE'
}
export const enum PEER_TYPE {
  LOCAL = 'LOCAL',
  REMOTE = 'REMOTE'
}
export const RTC_SOCKET_PATH = '/RTC_SOCKET_PATH'
export const CLIENT_URL = 'http://localhost:3000'
export const SERVER_PORT = 7001