export const RTC_OFFER_OPTION = {}
export const enum EventsEnum {
  SET_REMOTE_OFFER_DESCRIPTION = 'SET_LOCAL_OFFER_DESCRIPTION',
  SET_REMOTE_ANSWER_DESCRIPTION = 'SET_REMOTE_ANSWER_DESCRIPTION',
  ADD_REMOTE_ICE_CANDIDATE = 'ADD_REMOTE_ICE_CANDIDATE'
}