export const enum SocketEventsEnum {
  SET_OFFER_DESCRIPTION = 'SET_OFFER_DESCRIPTION',
  SET_ANSWER_DESCRIPTION = 'SET_ANSWER_DESCRIPTION',
  SET_ICE_CANDIDATE = 'SET_ICE_CANDIDATE',
  SET_LOCAL_ICE_CANDIDATE = 'SET_LOCAL_ICE_CANDIDATE'
}